# Generated by Django 5.0.1 on 2024-01-31 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=30)),
                ('i_photo', models.ImageField(upload_to='photos')),
                ('i_desc', models.TextField()),
                ('i_price', models.IntegerField()),
                ('i_quantity', models.IntegerField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email_id', models.CharField(blank=True, max_length=30)),
                ('phone_no', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('height', models.CharField(max_length=15)),
                ('weight', models.CharField(max_length=15)),
                ('address', models.TextField(default='')),
                ('l_date', models.DateField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('role', models.IntegerField()),
                ('status', models.IntegerField()),
                ('de_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deficiency')),
            ],
        ),
    ]
