# Generated by Django 5.0.1 on 2024-02-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email_id', models.CharField(blank=True, max_length=30)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wr_name', models.CharField(max_length=50)),
                ('b_name', models.CharField(max_length=70)),
                ('b_desc1', models.TextField(default='')),
                ('b_desc2', models.TextField(default='')),
                ('b_media', models.ImageField(upload_to='photos')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
                ('d_name2', models.CharField(max_length=30)),
                ('food_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=30)),
                ('weight_type', models.CharField(choices=[('Weight-gain', 'Weight-gain'), ('Weight-loose', 'Weight-loose')], max_length=30)),
                ('time_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=30)),
                ('calories', models.CharField(max_length=30)),
                ('calories2', models.CharField(max_length=30)),
                ('day', models.IntegerField()),
                ('diet_time', models.CharField(max_length=30)),
                ('de_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deficiency')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField()),
                ('comment', models.TextField()),
                ('f_date_time', models.DateTimeField(auto_now_add=True)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('o_date_time', models.DateTimeField(auto_now_add=True)),
                ('oid', models.IntegerField(null=True)),
                ('ostatus', models.IntegerField(null=True)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='placeorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamount', models.IntegerField(null=True)),
                ('o_date_time', models.DateTimeField(auto_now_add=True)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
